name: music_player
description: "Un reproductor de Música Libre"
publish_to: 'none'
version: 1.2.0

environment:
  sdk: ^3.5.0

dependencies:
  audio_video_progress_bar: ^2.0.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  just_audio: ^0.9.39
  just_audio_background: ^0.0.1-beta.17
  
  objectbox: ^4.3.0
  objectbox_flutter_libs: any
  on_audio_query:
    git:
      url: https://github.com/rozpo/on_audio_query
      ref: 0d78299
      path: packages/on_audio_query

  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  objectbox_generator: any

flutter:
  uses-material-design: true
